### PR TITLE
use .jsx extension

### PR DESCRIPTION
**Pull request by trungpham**

### CODE REVIEW

**Comment by knomedia** [comment]
@trungpham if you will rebase this, i'll merge it in. thanks!

**Comment by trungpham** [comment]
will do

**Comment by trungpham** [comment]
done

**Comment by knomedia** [comment]
thx!

**Comment by knomedia** [comment]
i've undone this in https://github.com/instructure-react/react-menu/commit/07b01f531aa6e21d3feae38aa593daa147b28eb2 for two reasons. 

1. it's caused issues in the test running (karma config stuff would need to be updated to with `extension` options to allow for `jsx` file extensions)

2. i don't know that i love having the `jsx` extensions. personal thing i suppose, but i don't like it.

you can always add `(js|jsx)` to your webpack config, of the project you are building to compensate

**Pull request merged**
